import type { ToolCategoryDefinition } from '@/types';

export const categoryDefinitions: ToolCategoryDefinition[] = [
  {
    id: 'cat-api-development',
    slug: 'api-development',
    name: 'API Development',
    description:
      'Tools for designing, building, testing, and documenting REST, GraphQL, and gRPC APIs.',
    icon: 'api',
    featured: true,
    order: 1,
  },
  {
    id: 'cat-databases',
    slug: 'databases',
    name: 'Databases',
    description: 'SQL, NoSQL, ORMs, query builders, and database management tools.',
    icon: 'database',
    featured: true,
    order: 2,
  },
  {
    id: 'cat-frontend',
    slug: 'frontend',
    name: 'Frontend',
    description: 'Frameworks, libraries, UI kits, and tools for building modern web interfaces.',
    icon: 'layout',
    featured: true,
    order: 3,
  },
  {
    id: 'cat-backend',
    slug: 'backend',
    name: 'Backend',
    description: 'Servers, frameworks, microservices, and server-side development tools.',
    icon: 'server',
    featured: true,
    order: 4,
  },
  {
    id: 'cat-testing',
    slug: 'testing',
    name: 'Testing',
    description: 'Unit, integration, end-to-end, and visual testing frameworks and services.',
    icon: 'shield-check',
    featured: false,
    order: 5,
  },
  {
    id: 'cat-monitoring',
    slug: 'monitoring',
    name: 'Monitoring',
    description: 'Logging, metrics, tracing, alerting, and observability platforms.',
    icon: 'activity',
    featured: false,
    order: 6,
  },
  {
    id: 'cat-security',
    slug: 'security',
    name: 'Security',
    description: 'Authentication, authorization, vulnerability scanning, and compliance tools.',
    icon: 'lock',
    featured: false,
    order: 7,
  },
  {
    id: 'cat-ci-cd',
    slug: 'ci-cd',
    name: 'CI/CD',
    description: 'Continuous integration, delivery, and deployment automation platforms.',
    icon: 'git-branch',
    featured: true,
    order: 8,
  },
  {
    id: 'cat-productivity',
    slug: 'productivity',
    name: 'Productivity',
    description: 'IDEs, editors, terminal tools, and automation that speed up development.',
    icon: 'zap',
    featured: false,
    order: 9,
  },
  {
    id: 'cat-design',
    slug: 'design',
    name: 'Design',
    description: 'UI/UX design, prototyping, and developer-designer collaboration tools.',
    icon: 'palette',
    featured: false,
    order: 10,
  },
  {
    id: 'cat-collaboration',
    slug: 'collaboration',
    name: 'Collaboration',
    description: 'Team chat, documentation, project management, and code review tools.',
    icon: 'users',
    featured: false,
    order: 11,
  },
  {
    id: 'cat-infrastructure',
    slug: 'infrastructure',
    name: 'Infrastructure',
    description: 'Cloud platforms, containers, orchestration, and infrastructure as code.',
    icon: 'cloud',
    featured: false,
    order: 12,
  },
];
